// Keep default workshop categories in A→Z order for consistent UI display.
export const WORKSHOP_CATEGORIES = [
  "Bamboo Craft",
  "Calligraphy",
  "Ceramics",
  "Fan Making",
  "Flower Arrangement",
  "Indigo Dyeing",
  "Incense",
  "Jewellery",
  "Kintsugi",
  "Kumihimo",
  "Lacquerware",
  "Leather Craft",
  "Maki-e",
  "Nihonga",
  "Paper Crafts",
  "Tea Ceremony",
  "Textiles",
  "Wagashi Making",
  "Woodblock Printing",
  "Yuzen",
];
